services:
    app.service.menu:
        class: AppBundle\Service\MenuService
        arguments: ['@app.mapper.menu']

    app.mapper.menu:
        class: AppBundle\Mapper\MenuMapper
        arguments: ['@doctrine.orm.entity_manager']

    app.twig.extension.menu:
        class: AppBundle\Twig\Extension\MenuExtension
        arguments: ['@app.service.menu']
        public: false
        tags:
            - { name: twig.extension }
